# Generated by Django 3.2 on 2021-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('orders', '0002_auto_20210913_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
