# Generated by Django 3.2 on 2021-09-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('KarateGi', 'KarateGi'), ('JudoGi', 'JudoGi'), ('Protectors', 'Protectors'), ('Belts', 'Belts'), ('Training Wear', 'Training Wear'), ('Bags', 'Bags')], max_length=120),
        ),
    ]
