# Generated by Django 3.2 on 2021-09-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Karate', 'Karate'), ('Judo', 'Judo'), ('Aikido', 'Aikido'), ('Boxing', 'Boxing'), ('Muai Tai', 'Muai Tai'), ('Training', 'Training'), ('Outdoor', 'Outdoor'), ('Shoes', 'Shoes')], max_length=120),
        ),
    ]
